[package]
name = "email-encoding"
version = "0.1.0"
description = "Low level email encoding RFCs implementations"
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"

[dependencies]
base64 = { version = "0.13", default-features = false }
memchr = "2.1"

[dev-dependencies]
pretty_assertions = "1"
